schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.100.2"
    hash = "sha256-wHV0FHvU4JjXh7h8reLpF+rdWJklx5DwsdrrDCTmjl0="
  [mod."cloud.google.com/go/compute"]
    version = "v1.6.1"
    hash = "sha256-S0BOrmPQOmzyMCEDIJJYyHa9YVImtJIYr5pH5+Ry1yI="
  [mod."cloud.google.com/go/iam"]
    version = "v0.3.0"
    hash = "sha256-/t1+ooeqksn8vSZhNFuWfQQpIQTxcN6nmeza2yorz0A="
  [mod."cloud.google.com/go/storage"]
    version = "v1.14.0"
    hash = "sha256-VyrDguWYk9ARFuX7ru6ElQjeMqytDgXs/RVQQ6HQDFM="
  [mod."cosmossdk.io/errors"]
    version = "v1.0.0-beta.7"
    hash = "sha256-XblGvIx6Wvvq6wggXjp+KbeJGXoe7AZH7hXEdauCezU="
  [mod."cosmossdk.io/math"]
    version = "v1.0.0-beta.3"
    hash = "sha256-lTQ27ZlL+kWlc+S//sJmyiOwaf9qS+YLv61I4OXi9XE="
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0-rc.1"
    hash = "sha256-3DboBqby2ejRU33FG96Z8JF5AJ8HP2rC/v++VyoQ2LQ="
  [mod."github.com/99designs/go-keychain"]
    version = "v0.0.0-20191008050251-8e49817e8af4"
    hash = "sha256-4EndKcspGC3GOPCmctXF1NnWzxWwMyY/OQpFMmr8Sc0="
  [mod."github.com/99designs/keyring"]
    version = "v1.2.1"
    hash = "sha256-OG3YGMFql9Vd5IzysdmyGjXhd39wQq0qh3YRQi4k7SI="
  [mod."github.com/ChainSafe/go-schnorrkel"]
    version = "v0.0.0-20200405005733-88cbf1b4c40d"
    hash = "sha256-i8RXZemJGlSjBT35oPm0SawFiBoIU5Pkq5xp4n/rzCY="
  [mod."github.com/Workiva/go-datastructures"]
    version = "v1.0.53"
    hash = "sha256-W6qOvqu8sokMlZrpOF1SWG138H0/BotywKNLlDF8Zug="
  [mod."github.com/armon/go-metrics"]
    version = "v0.4.0"
    hash = "sha256-mB6EFtn8BZ0u9TcJ6QTYw2SNAr4CnTVOMpiRKaoNH7k="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.40.45"
    hash = "sha256-7m4jOfXs356SUZG9tR+z3Yfa/O0CorkSkOXg/AmbqRM="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bgentry/go-netrc"]
    version = "v0.0.0-20140422174119-9fd32a8b3d3d"
    hash = "sha256-NDxQzO5C5M/aDz5/pjUHfZUh4VwIXovbb3irtxWCwjY="
  [mod."github.com/bgentry/speakeasy"]
    version = "v0.1.0"
    hash = "sha256-Gt1vj6CFovLnO6wX5u2O4UfecY9V2J9WGw1ez4HMrgk="
  [mod."github.com/btcsuite/btcd"]
    version = "v0.22.1"
    hash = "sha256-hBU+roIELcmbW2Gz7eGZzL9qNA1bakq5wNxqCgs4TKc="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.1.3"
    hash = "sha256-u6MEDopHoTWAZoVvvXOKnAg++xre53YgQx0gmf6t2KU="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/cockroachdb/apd/v2"]
    version = "v2.0.2"
    hash = "sha256-UrPHkvqVF8V78+kXKmjTHl79XsgDBnqFsje5BMYh0E4="
  [mod."github.com/coinbase/rosetta-sdk-go"]
    version = "v0.7.9"
    hash = "sha256-ZWIXIXcHGjeCNgMrpXymry8/8esDDauGFfF/+gEoO1Y="
  [mod."github.com/confio/ics23/go"]
    version = "v0.7.0"
    hash = "sha256-FjUQfDKtX+/13+UjJzbYPAkgM4GPZ0vk+dKz7/iRetw="
  [mod."github.com/confluentinc/bincover"]
    version = "v0.1.0"
    hash = "sha256-bMCtvBFSR8edk3gzCKSXCrR2a0LXBsJAlR5WjPZdKBE="
  [mod."github.com/cosmos/btcutil"]
    version = "v1.0.4"
    hash = "sha256-JvcBXBdjdmnaW/nyf/tw/uaOAGn1b78yxrtl2/Rs3kA="
  [mod."github.com/cosmos/cosmos-proto"]
    version = "v1.0.0-alpha7"
    hash = "sha256-2wCH+toTF2A6MfFjOa13muEH5oBCcxAhZEqirNOrBA0="
  [mod."github.com/cosmos/cosmos-sdk"]
    version = "v0.46.1"
    hash = "sha256-AZm3KzGee03chXTi6S/m0AZoGRkx4XLS6Rh2sBAWc30="
    replaced = "github.com/cosmos/cosmos-sdk"
  [mod."github.com/cosmos/go-bip39"]
    version = "v1.0.0"
    hash = "sha256-Qm2aC2vaS8tjtMUbHmlBSagOSqbduEEDwc51qvQaBmA="
  [mod."github.com/cosmos/gorocksdb"]
    version = "v1.2.0"
    hash = "sha256-209TcVuXc5s/TcOvNlaQ1HEJAUDTEK3nxPhs+d8TEcY="
  [mod."github.com/cosmos/iavl"]
    version = "v0.19.1"
    hash = "sha256-XrJeCNK0W8j3Qwxya4sr6R05zpI6+oYXFucWguiMiqM="
  [mod."github.com/cosmos/ibc-go/v5"]
    version = "v5.0.0-rc0"
    hash = "sha256-Rr4La316ikiQGrduriejY1uhezPyKjhyBWGcteZAm5Y="
  [mod."github.com/cosmos/ledger-cosmos-go"]
    version = "v0.11.2-0.20220719170349-e736b9afa7d1"
    hash = "sha256-4QMyAXATkY51jCI/9G//RjpkiQ+GweV048Ruy+s0pI8="
    replaced = "github.com/cosmos/ledger-cosmos-go"
  [mod."github.com/creachadair/taskgroup"]
    version = "v0.3.2"
    hash = "sha256-Y261IO/d9xjV0UScqHvo31broxvnKn4IQQC9Mu6jNkE="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.2"
    hash = "sha256-Nnklfg12vmWCOhELGyoRqEF4w4srp0WbPwreaChYLKs="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/desertbit/timer"]
    version = "v0.0.0-20180107155436-c41aec40b27f"
    hash = "sha256-abLOtEcomAqCWLphd2X6WkD/ED764w6sa6unox4BXss="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.0"
    hash = "sha256-01jneg1+1x8tTfUTBZ+6mHkQaqXVnPYxLJyJhJQcvt4="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/dvsekhvalnov/jose2go"]
    version = "v1.5.0"
    hash = "sha256-dsju6Xt83pe5SRPN/pUOnDUQByZ6hrhKIXWs3sSu7t8="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.1"
    hash = "sha256-TNXnnC/ZGNY9lInAcES1cBGqIdEljKuh5LH/khVFjVk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.5.4"
    hash = "sha256-iPuInpDAJvDeSTr6to713J/fTOWdQIWlLXWAuWIs2Bw="
  [mod."github.com/go-kit/kit"]
    version = "v0.12.0"
    hash = "sha256-5RkXo6s0oye8etgD5qy+AvkkkNsQ6jc0kWJj6flA4GM="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.5.1"
    hash = "sha256-t50m9ffvW8PiGvO+2svnLI+N/XaWaBS+ZlhwrEQn2gU="
  [mod."github.com/godbus/dbus"]
    version = "v0.0.0-20190726142602-4481cbc300e2"
    hash = "sha256-R7Gb9+Zjy80FbQSDGketoVEqfdOQKuOVTfWRjQ5kxZY="
  [mod."github.com/gogo/gateway"]
    version = "v1.1.0"
    hash = "sha256-OHcA3fEGZt4uYn6V5BAaDc47DkH7z0Al+v7MpkfeR8o="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.3-alpha.regen.1"
    hash = "sha256-TKa//aFXpWH+yK/cN1oaaqhipZpPUovekP6oA9vLIHY="
    replaced = "github.com/regen-network/protobuf"
  [mod."github.com/golang/glog"]
    version = "v1.0.0"
    hash = "sha256-bglITqRgzi52zc6FoYYnfCvrjFWV4RVOacPCnbEBom4="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/btree"]
    version = "v1.0.1"
    hash = "sha256-1PIeFGgUL4BK/StL/D12pg9bEQ5HfMT/fMLdus4pZTs="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/orderedcode"]
    version = "v0.0.1"
    hash = "sha256-KrExYovtUQrHGI1mPQf57jGw8soz7eWOC2xqEaV0uGk="
  [mod."github.com/google/renameio"]
    version = "v1.0.0"
    hash = "sha256-BB7pBAvdOPPkWvs0z5cVdt1QzKfO6mMlR6UEFgn0koE="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.4.0"
    hash = "sha256-zzat4+3iF2XBTQ6RZAUgsCbfK0HgO0nYhM4utA5dqz0="
  [mod."github.com/gorilla/handlers"]
    version = "v1.5.1"
    hash = "sha256-GnBAARgOx1E+hDMQ63SI17hdhGtLQxb31lZOmn5j/pU="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.3.0"
    hash = "sha256-seaTQMNz/lWzpR3ex2gSM1Yo2yD2q6bJQZvB1L3CONk="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/gsterjov/go-libsecret"]
    version = "v0.0.0-20161001094733-a6f4afe4910c"
    hash = "sha256-Z5upjItPU9onq5t7VzhdQFp13lMJrSiE3gNRapuK6ic="
  [mod."github.com/gtank/merlin"]
    version = "v0.1.1"
    hash = "sha256-tfP9DFdPIfAt29pCta6dObAABCbZt4y3ZActH6ERkr0="
  [mod."github.com/gtank/ristretto255"]
    version = "v0.1.2"
    hash = "sha256-fAoVTP1s5+f7/YtnzI+gaEz1MS+FuCgy3sT19ZHIxE4="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-getter"]
    version = "v1.6.1"
    hash = "sha256-WPCbbfFbE617EIUXxq81p3XrvhkSvYOeuiaR7n23nr0="
  [mod."github.com/hashicorp/go-immutable-radix"]
    version = "v1.3.1"
    hash = "sha256-65+A2HiVfS/GV9G+6/TkXXjzXhI/V98e6RlJWjxy+mg="
  [mod."github.com/hashicorp/go-safetemp"]
    version = "v1.0.0"
    hash = "sha256-g5i9m7FSRInQzZ4iRpIsoUu685AY7fppUwjhuZCezT8="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.6.0"
    hash = "sha256-UV0equpmW6BiJnp4W3TZlSJ+PTHuTA+CdOs2JTeHhjs="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.5-0.20210104140557-80c98217689d"
    hash = "sha256-w5utLMR7p5pF9xX+mI3N9NyfQ8ixNXNTgfXDu8fudmc="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hdevalence/ed25519consensus"]
    version = "v0.0.0-20220222234857-c00d1f31bab3"
    hash = "sha256-1ec2xc7l9oNtWJwVtx14HnozMZCe2DpfXmu1xI1Z/yo="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/improbable-eng/grpc-web"]
    version = "v0.15.0"
    hash = "sha256-9oqKb5Y3hjleOFE2BczbEzLH6q2Jg7kUTP/M8Yk4Ne4="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/jmhodges/levigo"]
    version = "v1.0.0"
    hash = "sha256-xEd0mDBeq3eR/GYeXjoTVb2sPs8sTCosn5ayWkcgENI="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.9"
    hash = "sha256-ctPxlVq0c/SoNPVsP66RjxUjTHys3diW2Apxjyc9WdE="
  [mod."github.com/lib/pq"]
    version = "v1.10.6"
    hash = "sha256-8EhFwY/9YH5L/fd6l2beOnC3VvpegRAmCCsnDVJBqBM="
  [mod."github.com/libp2p/go-buffer-pool"]
    version = "v0.1.0"
    hash = "sha256-wQqGTtRWsfR9n0O/SXHVgECebbnNmHddxJIbG63OJBQ="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.6"
    hash = "sha256-xToSfpuePctkTdhJtsuKIEkXwfMZbnkFT98ahIfd4wY="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.12"
    hash = "sha256-Y1vCt0ShrCz4wSmwsppCfeLPLKrWusc2zM2lUFwDMyI="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.14"
    hash = "sha256-e8zn5eCVh/B1HOP1PGXeXH0bGkIV0vKYP9KLwZni5as="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.2-0.20181231171920-c182affec369"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mimoo/StrobeGo"]
    version = "v0.0.0-20181016162300-f8f6d4d2b643"
    hash = "sha256-ih5WfC48IniPuAHUpC6upOabZA1/DssTAcxhZe6A/dE="
  [mod."github.com/minio/highwayhash"]
    version = "v1.0.2"
    hash = "sha256-UeHeepKtToyA5e/w3KdmpbCn+4medesZG0cAcU6P2cY="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-testing-interface"]
    version = "v1.0.0"
    hash = "sha256-/Dpv/4i5xuK8hDH+q8YTdF6Jg6NNtfO4Wqig2JCWgrY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mtibben/percent"]
    version = "v0.2.1"
    hash = "sha256-Zj1lpCP6mKQ0UUTMs2By4LC414ou+iJzKkK+eBHfEcc="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.2"
    hash = "sha256-z3JgSi7AKZul1Ta5NwpLVebKw30mGUKc+ijssiAClVU="
  [mod."github.com/petermattis/goid"]
    version = "v0.0.0-20180202154549-b0b1615b78e5"
    hash = "sha256-TCyVuP7rAtrvlterVCapFtbf6UmIf72FXQvkQoDtDj4="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.12.2"
    hash = "sha256-d8xHyML/FImuPmFOy7UGW/y85NPLzJYL6IFhR3s7XzE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.34.0"
    hash = "sha256-M+v+7DntUBmiQNzfNmG3aLLufbl0XBQOubtYoNTzJDA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.3"
    hash = "sha256-ik0WpnpSjMwifPYfQTfu/eb5ilNj+eLJF0d5Dftp8A8="
  [mod."github.com/rakyll/statik"]
    version = "v0.1.7"
    hash = "sha256-/bfnXHBmN8vviPL7D85IzcEVXCaWyjbPPNyauzEcQ8Q="
  [mod."github.com/rcrowley/go-metrics"]
    version = "v0.0.0-20200313005456-10cdbea86bc0"
    hash = "sha256-xHqWWd4/RyAxqb80zjnrqHnHtWPfVTyByE+vDfbT52E="
  [mod."github.com/regen-network/cosmos-proto"]
    version = "v0.3.1"
    hash = "sha256-Bchbq/Hg72EA7Hevs8+PNuENuQaZAzk3qeVjMqFMUxc="
  [mod."github.com/rs/cors"]
    version = "v1.8.2"
    hash = "sha256-FxBbQVb8zIoDGGaAJKfsYV0+POkh1tyX7P6A/Lk5Vsc="
  [mod."github.com/rs/zerolog"]
    version = "v1.27.0"
    hash = "sha256-BxQtP2TROeSSpj9l1irocuSfxn55UL4ugzB/og7r8eE="
  [mod."github.com/sasha-s/go-deadlock"]
    version = "v0.2.1-0.20190427202633-1595213edefa"
    hash = "sha256-BBOohTR+ktgJHAoYWh39/ui8MczcJECloc7tvxVBE50="
  [mod."github.com/spf13/afero"]
    version = "v1.8.2"
    hash = "sha256-ERuG4GK1LOn72DRbT9URpo1QoVIm2A3mPtlf+xSPgx8="
  [mod."github.com/spf13/cast"]
    version = "v1.5.0"
    hash = "sha256-Pdp+wC5FWqyJKzyYHb7JCcV9BoJk/sxQw6nLyuLJvuQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.5.0"
    hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.12.0"
    hash = "sha256-51kkvy5tGqdyNgQgZWG5WRYnjgCwwGyuIGZsIdPB2n0="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.0"
    hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="
  [mod."github.com/subosito/gotenv"]
    version = "v1.4.0"
    hash = "sha256-H5mdiXO7LZ7ggJMjeiOLGWa1UbweXy/10KwEpFOrPv8="
  [mod."github.com/syndtr/goleveldb"]
    version = "v1.0.1-0.20210819022825-2ae1ddf74ef7"
    hash = "sha256-36a4hgVQfwtS2zhylKpQuFhrjdc/Y8pF0dxc26jcZIU="
  [mod."github.com/tendermint/btcd"]
    version = "v0.1.1"
    hash = "sha256-QQl2GWZaKQtd+LQrgx2unkTLI1qye57fCWwJcmCXT/0="
  [mod."github.com/tendermint/crypto"]
    version = "v0.0.0-20191022145703-50d29ede1e15"
    hash = "sha256-NkoZ3hKWZt5Hca49I+1g81x1m6aQGELZ/QGLdb3uHm4="
  [mod."github.com/tendermint/go-amino"]
    version = "v0.16.0"
    hash = "sha256-JW4zO/0vMzf1dXLePOqaMtiLUZgNbuIseh9GV+jQlf0="
  [mod."github.com/tendermint/tendermint"]
    version = "v0.34.21"
    hash = "sha256-C1KW6Wd4TwsFC09IHt8Jo3dozEk/Q2ZVdTapM8btEJ0="
  [mod."github.com/tendermint/tm-db"]
    version = "v0.6.7"
    hash = "sha256-hl/3RrBrpkk2zA6dmrNlIYKs1/GfqegSscDSkA5Pjlo="
  [mod."github.com/tidwall/gjson"]
    version = "v1.14.0"
    hash = "sha256-TiMGdAn840a2tOsi5mQ6fAK62ohvY6zuoVaUHCTyIwA="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.8"
    hash = "sha256-bfG3dssBUn+mSOAuKL+a/DTGGLUA+eASgLoGv/Gkqs0="
  [mod."github.com/zondax/hid"]
    version = "v0.9.0"
    hash = "sha256-PvXtxXo/3C+DS9ZeGBlr4zXbIpaYNtMqLzxYhusFXNY="
    replaced = "github.com/zondax/hid"
  [mod."github.com/zondax/ledger-go"]
    version = "v0.12.2"
    hash = "sha256-hskkGuj33eP7WRY6A1R6daC2fpsgVgoaDrnu7heKL0M="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."go.opencensus.io"]
    version = "v0.23.0"
    hash = "sha256-R3O9GyNtv6j0ic7s+2xkLLaLzbJEop0Otj1nJDFBjsg="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220525230936-793ad666bf5e"
    hash = "sha256-xc+juPFuN1rbn+hqHuLNO39KFilw4aAm6NnxeKMAI+0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220722155223-a9213eeb770e"
    hash = "sha256-kNgzydWRpjm0sZl4uXEs3LX5L0xjJtJRAFf/CTlYUN4="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220726230323-06994584191e"
    hash = "sha256-VFJB2BjvFZnp0zoJLX4iinV/P6Cn7XUlsKwBGCdVjlU="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20220411215720-9780585627b5"
    hash = "sha256-PubcNZWej7Pb8TnHNfXPkRo3Gj91YfePvvN5ImftEbs="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220727055044-e65921a090b8"
    hash = "sha256-WIJmjjYnZ3XY7BhbskCdNHCVGK7lxUeYpEegmYWSHe8="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20220722155259-a9ba230a4035"
    hash = "sha256-9uM1OONzbsa6bz2iKk767hAaCuafi58bdTF7at03fWY="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20220517211312-f3a8303e98df"
    hash = "sha256-DaZLVDk7I1uScyvUeHGyosnGm6xZNq6XIJlJfwaX6hs="
  [mod."google.golang.org/api"]
    version = "v0.81.0"
    hash = "sha256-hG/Wanchjq75ymZy59/Rl8S9tl9Xw3x1gdjYCpkNfB8="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220725144611-272f38e5d71b"
    hash = "sha256-/6ELCTRAvCdKnJQohk71UEJobDkAF2Gx09/SDXit6Go="
  [mod."google.golang.org/grpc"]
    version = "v1.48.0"
    hash = "sha256-sF2W+L5IHiCO1t/SsHpmht1tPiXJ2RBiiosk+BngfKA="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/ini.v1"]
    version = "v1.66.6"
    hash = "sha256-icGrattKhCLweSJqNhyOs6AavHapLFaOQ9xCA8wID08="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."nhooyr.io/websocket"]
    version = "v1.8.6"
    hash = "sha256-DyaiCc/1iELrl6JSpz6WYMtFwUiSCOSoNF8IhSyP1ag="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
