schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0-beta.2"
    hash = "sha256-pcbcYR1Kiarajit0b6f4/SDHap8jkLXmkiblMLWuZrs="
  [mod."github.com/99designs/keyring"]
    version = "v1.1.6-fixes"
    hash = "sha256-zrZrmSenvQRi63wHBgVtV93uuUaM1GBGuO5Fi1oNPzE="
    replaced = "github.com/crypto-org-chain/keyring"
  [mod."github.com/ChainSafe/go-schnorrkel"]
    version = "v0.0.0-20200405005733-88cbf1b4c40d"
    hash = "sha256-i8RXZemJGlSjBT35oPm0SawFiBoIU5Pkq5xp4n/rzCY="
  [mod."github.com/DataDog/zstd"]
    version = "v1.4.5"
    hash = "sha256-WFHcU2EFRIIc1wSc0jN2VPeJzBMcZTIN5LFNBFk+NAY="
  [mod."github.com/Workiva/go-datastructures"]
    version = "v1.0.53"
    hash = "sha256-W6qOvqu8sokMlZrpOF1SWG138H0/BotywKNLlDF8Zug="
  [mod."github.com/armon/go-metrics"]
    version = "v0.3.10"
    hash = "sha256-QoehptDXOyi8HimcsBSjtHNp3zsit5DByKJ3rnHIzB8="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bgentry/speakeasy"]
    version = "v0.1.0"
    hash = "sha256-Gt1vj6CFovLnO6wX5u2O4UfecY9V2J9WGw1ez4HMrgk="
  [mod."github.com/btcsuite/btcd"]
    version = "v0.22.1"
    hash = "sha256-hBU+roIELcmbW2Gz7eGZzL9qNA1bakq5wNxqCgs4TKc="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/coinbase/rosetta-sdk-go"]
    version = "v0.7.0"
    hash = "sha256-W4cY7vr/+f6zjmO16WxF7XQBhW5mVrEfpYTNcu+y8yo="
  [mod."github.com/confio/ics23/go"]
    version = "v0.8.0"
    hash = "sha256-mFKxFHp7RaE1L5NdtH9H9px2Cy6I5uOZVnFOgE8Nrew="
    replaced = "github.com/cosmos/cosmos-sdk/ics23/go"
  [mod."github.com/confluentinc/bincover"]
    version = "v0.1.0"
    hash = "sha256-bMCtvBFSR8edk3gzCKSXCrR2a0LXBsJAlR5WjPZdKBE="
  [mod."github.com/cosmos/btcutil"]
    version = "v1.0.4"
    hash = "sha256-JvcBXBdjdmnaW/nyf/tw/uaOAGn1b78yxrtl2/Rs3kA="
  [mod."github.com/cosmos/cosmos-sdk"]
    version = "v0.44.8-patch-dragonberry"
    hash = "sha256-/B6IwWo5+R3byA0ulFIQJgk/mn0M9t855pa/wcxZeqU="
    replaced = "github.com/crypto-org-chain/cosmos-sdk"
  [mod."github.com/cosmos/go-bip39"]
    version = "v1.0.0"
    hash = "sha256-Qm2aC2vaS8tjtMUbHmlBSagOSqbduEEDwc51qvQaBmA="
  [mod."github.com/cosmos/gorocksdb"]
    version = "v1.2.0"
    hash = "sha256-209TcVuXc5s/TcOvNlaQ1HEJAUDTEK3nxPhs+d8TEcY="
  [mod."github.com/cosmos/iavl"]
    version = "v0.19.2-0.20220916140702-9b6be3095313"
    hash = "sha256-49xr/7/4L1wZ45eW5lE7C4SlcbGf4gBY+662SfJiWPQ="
  [mod."github.com/cosmos/ibc-go/v2"]
    version = "v2.0.4"
    hash = "sha256-FiARi0pH33L+fOWYoJmSGiHupGVUfP5gB/nsWmatPiU="
  [mod."github.com/cosmos/ledger-cosmos-go"]
    version = "v0.9.10-0.20200929055312-01e1d341de0f"
    hash = "sha256-YD8G/BZH7Ytb3FFyh9e41V9XbTBzFSdB5lQ8PdgrX7Y="
    replaced = "github.com/crypto-com/ledger-cosmos-go"
  [mod."github.com/cosmos/ledger-go"]
    version = "v0.9.2"
    hash = "sha256-0YI+0A6wFBjiebBwzWOQjkgXkTakCrf7Gjg2xEaQdoM="
  [mod."github.com/creachadair/taskgroup"]
    version = "v0.3.2"
    hash = "sha256-Y261IO/d9xjV0UScqHvo31broxvnKn4IQQC9Mu6jNkE="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.0"
    hash = "sha256-sW90eNnxmYBGY+uQe9tH97CCHdRvNuseWhicySnKlDo="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/desertbit/timer"]
    version = "v0.0.0-20180107155436-c41aec40b27f"
    hash = "sha256-abLOtEcomAqCWLphd2X6WkD/ED764w6sa6unox4BXss="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.2"
    hash = "sha256-qd12+k05ooJG+eaD3UN/UK/bUyH8KZQ4GfTnNR/Xw4U="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.0.3"
    hash = "sha256-z2vtpbiCNNfaysPEdOCgcyuPVM8jds1bcfegDJaRSew="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/dvsekhvalnov/jose2go"]
    version = "v0.0.0-20200901110807-248326c1351b"
    hash = "sha256-+ogb8WGT1LQbXmzhpiGd0gWg4x4Wyn5Rt7Soa5Il8hs="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.2"
    hash = "sha256-hj6FZQ1fDAV+1wGIViAt8XaAkWZ1I5vJzgjIJa7XRBA="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.5.4"
    hash = "sha256-iPuInpDAJvDeSTr6to713J/fTOWdQIWlLXWAuWIs2Bw="
  [mod."github.com/go-kit/kit"]
    version = "v0.12.0"
    hash = "sha256-5RkXo6s0oye8etgD5qy+AvkkkNsQ6jc0kWJj6flA4GM="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.5.1"
    hash = "sha256-t50m9ffvW8PiGvO+2svnLI+N/XaWaBS+ZlhwrEQn2gU="
  [mod."github.com/godbus/dbus"]
    version = "v0.0.0-20190726142602-4481cbc300e2"
    hash = "sha256-R7Gb9+Zjy80FbQSDGketoVEqfdOQKuOVTfWRjQ5kxZY="
  [mod."github.com/gogo/gateway"]
    version = "v1.1.0"
    hash = "sha256-OHcA3fEGZt4uYn6V5BAaDc47DkH7z0Al+v7MpkfeR8o="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.3-alpha.regen.1"
    hash = "sha256-TKa//aFXpWH+yK/cN1oaaqhipZpPUovekP6oA9vLIHY="
    replaced = "github.com/regen-network/protobuf"
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.3"
    hash = "sha256-77y8JFRE3FcYd8CTypXnJlTJuog1pJg5WjhboFjTiLU="
  [mod."github.com/google/btree"]
    version = "v1.0.1"
    hash = "sha256-1PIeFGgUL4BK/StL/D12pg9bEQ5HfMT/fMLdus4pZTs="
  [mod."github.com/google/orderedcode"]
    version = "v0.0.1"
    hash = "sha256-KrExYovtUQrHGI1mPQf57jGw8soz7eWOC2xqEaV0uGk="
  [mod."github.com/google/renameio"]
    version = "v1.0.0"
    hash = "sha256-BB7pBAvdOPPkWvs0z5cVdt1QzKfO6mMlR6UEFgn0koE="
  [mod."github.com/gorilla/handlers"]
    version = "v1.5.1"
    hash = "sha256-GnBAARgOx1E+hDMQ63SI17hdhGtLQxb31lZOmn5j/pU="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.3.0"
    hash = "sha256-seaTQMNz/lWzpR3ex2gSM1Yo2yD2q6bJQZvB1L3CONk="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/gsterjov/go-libsecret"]
    version = "v0.0.0-20161001094733-a6f4afe4910c"
    hash = "sha256-Z5upjItPU9onq5t7VzhdQFp13lMJrSiE3gNRapuK6ic="
  [mod."github.com/gtank/merlin"]
    version = "v0.1.1"
    hash = "sha256-tfP9DFdPIfAt29pCta6dObAABCbZt4y3ZActH6ERkr0="
  [mod."github.com/gtank/ristretto255"]
    version = "v0.1.2"
    hash = "sha256-fAoVTP1s5+f7/YtnzI+gaEz1MS+FuCgy3sT19ZHIxE4="
  [mod."github.com/hashicorp/go-immutable-radix"]
    version = "v1.3.1"
    hash = "sha256-65+A2HiVfS/GV9G+6/TkXXjzXhI/V98e6RlJWjxy+mg="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hdevalence/ed25519consensus"]
    version = "v0.0.0-20210204194344-59a8610d2b87"
    hash = "sha256-QgOyyg2phYmreWbMzuSgDVY/unUUZhmbFsqvShCKgFs="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/improbable-eng/grpc-web"]
    version = "v0.14.1"
    hash = "sha256-TH0z93gey2WF6nWRJ5N0sbKkEmAMNj/hJiNC6RR0/qw="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.1"
    hash = "sha256-ZTP9pLgwAAvHYK5A4PqwWCHGt00x5zMSOpCPoomQ3Sg="
  [mod."github.com/jmhodges/levigo"]
    version = "v1.0.0"
    hash = "sha256-xEd0mDBeq3eR/GYeXjoTVb2sPs8sTCosn5ayWkcgENI="
  [mod."github.com/keybase/go-keychain"]
    version = "v0.0.0-20190712205309-48d3d31d256d"
    hash = "sha256-bn04wkDnhQ0tb/YzmPf7MNJlApOl+z6+EAbUqH7Ti5Q="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.9"
    hash = "sha256-ctPxlVq0c/SoNPVsP66RjxUjTHys3diW2Apxjyc9WdE="
  [mod."github.com/lib/pq"]
    version = "v1.10.6"
    hash = "sha256-8EhFwY/9YH5L/fd6l2beOnC3VvpegRAmCCsnDVJBqBM="
  [mod."github.com/libp2p/go-buffer-pool"]
    version = "v0.1.0"
    hash = "sha256-wQqGTtRWsfR9n0O/SXHVgECebbnNmHddxJIbG63OJBQ="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.6"
    hash = "sha256-xToSfpuePctkTdhJtsuKIEkXwfMZbnkFT98ahIfd4wY="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.2-0.20181231171920-c182affec369"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mimoo/StrobeGo"]
    version = "v0.0.0-20210601165009-122bf33a46e0"
    hash = "sha256-rmw70RHsbeOnema++aFCPdswADMVKtb7KGF3msOI7ak="
  [mod."github.com/minio/highwayhash"]
    version = "v1.0.2"
    hash = "sha256-UeHeepKtToyA5e/w3KdmpbCn+4medesZG0cAcU6P2cY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mtibben/percent"]
    version = "v0.2.1"
    hash = "sha256-Zj1lpCP6mKQ0UUTMs2By4LC414ou+iJzKkK+eBHfEcc="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.5"
    hash = "sha256-YWdHmuCGliWfiH0tTHuf07AAn/zOJNoq7g+5fvqdnrQ="
  [mod."github.com/petermattis/goid"]
    version = "v0.0.0-20180202154549-b0b1615b78e5"
    hash = "sha256-TCyVuP7rAtrvlterVCapFtbf6UmIf72FXQvkQoDtDj4="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.12.2"
    hash = "sha256-d8xHyML/FImuPmFOy7UGW/y85NPLzJYL6IFhR3s7XzE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.34.0"
    hash = "sha256-M+v+7DntUBmiQNzfNmG3aLLufbl0XBQOubtYoNTzJDA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.3"
    hash = "sha256-ik0WpnpSjMwifPYfQTfu/eb5ilNj+eLJF0d5Dftp8A8="
  [mod."github.com/rakyll/statik"]
    version = "v0.1.7"
    hash = "sha256-/bfnXHBmN8vviPL7D85IzcEVXCaWyjbPPNyauzEcQ8Q="
  [mod."github.com/rcrowley/go-metrics"]
    version = "v0.0.0-20201227073835-cf1acfcdf475"
    hash = "sha256-10ytHQ1SpMKYTiKuOPdEMuOVa8HVvv9ryYSIF9BHEBI="
  [mod."github.com/regen-network/cosmos-proto"]
    version = "v0.3.1"
    hash = "sha256-Bchbq/Hg72EA7Hevs8+PNuENuQaZAzk3qeVjMqFMUxc="
  [mod."github.com/rs/cors"]
    version = "v1.8.2"
    hash = "sha256-FxBbQVb8zIoDGGaAJKfsYV0+POkh1tyX7P6A/Lk5Vsc="
  [mod."github.com/rs/zerolog"]
    version = "v1.27.0"
    hash = "sha256-BxQtP2TROeSSpj9l1irocuSfxn55UL4ugzB/og7r8eE="
  [mod."github.com/sasha-s/go-deadlock"]
    version = "v0.3.1"
    hash = "sha256-2CBEi9/iN/OMt7wEIG+hRjgDH6CRWIgibGGGy1dQ78I="
  [mod."github.com/spf13/afero"]
    version = "v1.8.2"
    hash = "sha256-ERuG4GK1LOn72DRbT9URpo1QoVIm2A3mPtlf+xSPgx8="
  [mod."github.com/spf13/cast"]
    version = "v1.5.0"
    hash = "sha256-Pdp+wC5FWqyJKzyYHb7JCcV9BoJk/sxQw6nLyuLJvuQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.5.0"
    hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.13.0"
    hash = "sha256-yHviS3lMo1hB6jwyiU3zpyGtxP6v9AsyZUKiLeCVz+k="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.0"
    hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="
  [mod."github.com/subosito/gotenv"]
    version = "v1.4.1"
    hash = "sha256-aHAUs8Gh+BREUulljWr7vBZQg1BLu/M/8UfNK8CWSn8="
  [mod."github.com/syndtr/goleveldb"]
    version = "v1.0.1-0.20200815110645-5c35d600f0ca"
    hash = "sha256-59eJ01Q7GsEIXrORY5onzkowKo1DUEbm+3CCG//yWHM="
  [mod."github.com/tendermint/btcd"]
    version = "v0.1.1"
    hash = "sha256-QQl2GWZaKQtd+LQrgx2unkTLI1qye57fCWwJcmCXT/0="
  [mod."github.com/tendermint/crypto"]
    version = "v0.0.0-20191022145703-50d29ede1e15"
    hash = "sha256-NkoZ3hKWZt5Hca49I+1g81x1m6aQGELZ/QGLdb3uHm4="
  [mod."github.com/tendermint/go-amino"]
    version = "v0.16.0"
    hash = "sha256-JW4zO/0vMzf1dXLePOqaMtiLUZgNbuIseh9GV+jQlf0="
  [mod."github.com/tendermint/tendermint"]
    version = "v0.34.22"
    hash = "sha256-4p4cpyCWjBbNQUpYN2gDJvnyj+Pov9hw5uRjHrrO++Y="
    replaced = "github.com/tendermint/tendermint"
  [mod."github.com/tendermint/tm-db"]
    version = "v0.6.7"
    hash = "sha256-hl/3RrBrpkk2zA6dmrNlIYKs1/GfqegSscDSkA5Pjlo="
  [mod."github.com/tidwall/gjson"]
    version = "v1.9.3"
    hash = "sha256-EUaWUTATM2UrGZKyYvKkmU9bEPmfMIRmZ84Nc3nJgh0="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/zondax/hid"]
    version = "v0.9.0"
    hash = "sha256-PvXtxXo/3C+DS9ZeGBlr4zXbIpaYNtMqLzxYhusFXNY="
  [mod."github.com/zondax/ledger-go"]
    version = "v0.12.1"
    hash = "sha256-/az4HRrqTyNlae8HtsSj6D3Q7vu2DXx4KoI5ifF0t6E="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220722155217-630584e8d5aa"
    hash = "sha256-gLzdWnyJtT1z2lw/GGmJEFBZ7AS1qVAo8M9Fqi0xFuE="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220812174116-3211cb980234"
    hash = "sha256-v/Qep/W6lw6IurR+R2V0AN/MlQUROLnEaWeeuwY8sg8="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220818161305-2296e01440c6"
    hash = "sha256-gCzekaAZ7aPg4EUAwL3USir4BNp/Etv5OWGekAGVZ8w="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20220722155259-a9ba230a4035"
    hash = "sha256-9uM1OONzbsa6bz2iKk767hAaCuafi58bdTF7at03fWY="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220725144611-272f38e5d71b"
    hash = "sha256-/6ELCTRAvCdKnJQohk71UEJobDkAF2Gx09/SDXit6Go="
  [mod."google.golang.org/grpc"]
    version = "v1.33.2"
    hash = "sha256-0vOeuHDvRviofJmr4dOzUh4Y1y2X6ujGCcLcICVnQ0Q="
    replaced = "google.golang.org/grpc"
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."nhooyr.io/websocket"]
    version = "v1.8.6"
    hash = "sha256-DyaiCc/1iELrl6JSpz6WYMtFwUiSCOSoNF8IhSyP1ag="
