stakingtest:
  validators:
    - coins: 10cro
      staked: 10cro
    - coins: 10cro
      staked: 10cro
    - coins: 1cro
      staked: 1cro
      min_self_delegation: 10000000  # 0.1cro
  accounts:
    - name: community
      coins: 100cro
    - name: ecosystem
      coins: 200cro
    - name: reserve
      coins: 200cro
      vesting: "60s"
    - name: launch
      coins: 100cro
    - name: signer1
      coins: 10000cro
    - name: signer2
      coins: 2000cro
  genesis:
    app_state:
      staking:
        params:
          unbonding_time: "10s"
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "basecro"
              amount: "10000000"
