[tool.poetry]
name = "integration_tests"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.4.0"
pytest-xdist = "^1.34.0"
flake8 = "^3.8.4"
black = "^20.8b1"
flake8-black = "^0.2.1"
flake8-isort = "^4.0.0"
pep8-naming = "^0.11.1"
pytest-github-actions-annotate-failures = "^0.1.1"
PyYAML = "^5.3.1"
protobuf = "3.19.4"
python-dateutil = "^2.8.1"
pystarport = "0.2.4"
# TODO: Fix to a version after chainlibpy released the new gRPC changes
chainlibpy = { git = "https://github.com/crypto-org-chain/chainlibpy.git", branch = "master" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
